<?php
/**
 * SScribe Admin
 *
 * @package SScribe_Export_Site_Pages
 * @license GPL v2 or later
 * @link    https://www.gnu.org/licenses/gpl-2.0.html
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Admin functionality for SScribe plugin.
 */
class SScribe_Admin {

	/**
	 * Page collector service.
	 *
	 * @var SScribe_Page_Collector
	 */
	private SScribe_Page_Collector $collector;

	/**
	 * SEO reader service.
	 *
	 * @var SScribe_SEO_Reader
	 */
	private SScribe_SEO_Reader $seo_reader;

	/**
	 * Zip handler service.
	 *
	 * @var SScribe_Zip_Handler
	 */
	private readonly SScribe_Zip_Handler $zip_handler;

	/**
	 * Debug console handler.
	 *
	 * @var SScribe_Admin_Debug
	 */
	private SScribe_Admin_Debug $debug;

	/**
	 * CSP nonce for script tags.
	 *
	 * @var string
	 */
	private string $csp_nonce = '';

	/**
	 * Initialize the admin interface.
	 *
	 * @param SScribe_Page_Collector|null $collector   Page collector.
	 * @param SScribe_SEO_Reader|null     $seo_reader  SEO reader.
	 * @param SScribe_Zip_Handler|null    $zip_handler Zip handler.
	 */
	public function __construct(
		?SScribe_Page_Collector $collector = null,
		?SScribe_SEO_Reader $seo_reader = null,
		?SScribe_Zip_Handler $zip_handler = null
	) {
		$this->collector   = $collector ?? new SScribe_Page_Collector();
		$this->seo_reader  = $seo_reader ?? new SScribe_SEO_Reader();
		$this->zip_handler = $zip_handler ?? new SScribe_Zip_Handler();

		$this->debug = new SScribe_Admin_Debug();
		// Always register debug AJAX hooks so the debug tab can toggle
		// settings even when debug logging is currently disabled.
		$this->debug->register_hooks();
	}

	/**
	 * Add the admin menu page.
	 */
	public function add_admin_menu(): void {
		add_menu_page(
			__( 'SScribe Export', 'sscribe-export-site-pages' ),
			__( 'SScribe Export', 'sscribe-export-site-pages' ),
			$this->get_required_capability(),
			'sscribe-export',
			array( $this, 'render_admin_page' ),
			'dashicons-media-document',
			58
		);
	}

	/**
	 * Get the capability required to access export functions.
	 *
	 * @return string Capability name.
	 */
	private function get_required_capability(): string {
		return SScribe_Capabilities::get_required();
	}

	/**
	 * Get a nonce for download actions.
	 *
	 * @return string Nonce value.
	 */
	private function get_download_nonce(): string {
		return wp_create_nonce( 'sscribe_download' );
	}

	/**
	 * Get a CSP nonce for inline scripts.
	 *
	 * Generates a per-request cryptographic nonce for CSP script-src directive.
	 * The nonce is generated once on first call (lazy-init) and reused for all
	 * subsequent calls. This ensures the same nonce value is used in both the
	 * CSP header and when enqueueing scripts.
	 *
	 * @return string CSP nonce value.
	 */
	public function get_csp_nonce(): string {
		if ( empty( $this->csp_nonce ) ) {
			$this->csp_nonce = bin2hex( random_bytes( 16 ) );
		}
		return $this->csp_nonce;
	}

	/**
	 * Add CSP nonce to script tags for this plugin.
	 *
	 * Hooks into WordPress script_loader_tag filter to inject the nonce
	 * attribute into script tags generated by wp_enqueue_script().
	 *
	 * @param string $tag    The script tag HTML.
	 * @param string $handle The script handle.
	 * @param string $src    The script source URL.
	 * @return string Modified script tag with nonce attribute.
	 */
	public function add_nonce_to_script_tags( string $tag, string $handle, string $src ): string {
		// Only add nonce to our plugin's scripts.
		$our_handles = array( 'sscribe-admin', 'sscribe-debug-console' );

		if ( ! in_array( $handle, $our_handles, true ) ) {
			return $tag;
		}

		$nonce = $this->get_csp_nonce();
		if ( empty( $nonce ) ) {
			return $tag;
		}

		// Add nonce attribute to script tag.
		return str_replace( '<script ', '<script nonce="' . esc_attr( $nonce ) . '" ', $tag );
	}

	/**
	 * Redirect to the plugin page after activation.
	 */
	public function maybe_redirect_after_activation(): void {
		if ( wp_doing_ajax() || ! is_admin() || wp_doing_cron() || ( defined( 'WP_CLI' ) && WP_CLI ) ) {
			return;
		}

		if ( ! get_transient( 'sscribe_activation_redirect' ) ) {
			return;
		}

		if ( ! current_user_can( $this->get_required_capability() ) ) {
			delete_transient( 'sscribe_activation_redirect' );
			return;
		}

		delete_transient( 'sscribe_activation_redirect' );

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Redirect guard only checks activation flow markers.
		if ( isset( $_GET['activate-multi'] ) && '1' === sanitize_key( (string) $_GET['activate-multi'] ) ) {
			return;
		}

		$this->redirect_to_plugin_page();
	}

	/**
	 * Redirect to the plugin's main admin page.
	 */
	protected function redirect_to_plugin_page(): void {
		wp_safe_redirect( admin_url( 'admin.php?page=sscribe-export' ) );
		exit;
	}

	/**
	 * Send security headers on the export page.
	 *
	 * The `Content-Security-Policy` header is intentionally permissive
	 * on `script-src` because the WP admin loads scripts from many
	 * sources (core, our plugin, third-party admin plugins) and
	 * nonce-locking the WP nonce on script-src would break those
	 * scripts. The restrictive directives that follow (`object-src`,
	 * `base-uri`, `frame-ancestors`) are chosen to be defense-in-depth
	 * without breaking admin JS:
	 *
	 *  - `object-src 'none'` blocks <object>/<embed>/<applet> — the
	 *    classic vector for XSS via Flash and PDF readers.
	 *  - `base-uri 'self'` blocks <base> tag injection that could
	 *    re-target relative URLs to an attacker domain.
	 *  - `frame-ancestors 'self'` supersedes X-Frame-Options for
	 *    browsers that recognize CSP Level 2 (all evergreen browsers).
	 *  - `form-action 'self'` prevents the admin form from posting to
	 *    an external origin.
	 *
	 * WordPress core does not set a CSP on admin pages, so this is
	 * additive defense.
	 */
	public function maybe_send_csp_headers(): void {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only page param check.
		if ( ! isset( $_GET['page'] ) || 'sscribe-export' !== sanitize_key( $_GET['page'] ) ) {
			return;
		}

		if ( headers_sent() ) {
			return;
		}

		$nonce = $this->get_csp_nonce();

		header( 'X-Frame-Options: SAMEORIGIN' );
		header( 'X-Content-Type-Options: nosniff' );
		header( 'Referrer-Policy: strict-origin-when-cross-origin' );
		header(
			'Content-Security-Policy: ' .
			"default-src 'self'; " .
			"script-src 'self' 'nonce-" . $nonce . "' 'unsafe-inline'; " .
			"style-src 'self' 'unsafe-inline'; " .
			"img-src 'self' data: https:; " .
			"object-src 'none'; " .
			"base-uri 'self'; " .
			"frame-ancestors 'self'; " .
			"form-action 'self'"
		);
		header( 'Permissions-Policy: geolocation=(), microphone=(), camera=()' );
	}

	/**
	 * Load admin CSS and JS on the export page.
	 *
	 * @param string $hook_suffix Current admin page hook.
	 */
	public function enqueue_admin_assets( string $hook_suffix ): void {

		if ( 'toplevel_page_sscribe-export' !== $hook_suffix ) {
			return;
		}

		$css_version = file_exists( SSCRIBE_PLUGIN_DIR . 'admin/css/sscribe-admin.css' )
			? filemtime( SSCRIBE_PLUGIN_DIR . 'admin/css/sscribe-admin.css' )
			: SSCRIBE_VERSION;

		$js_version = file_exists( SSCRIBE_PLUGIN_DIR . 'admin/js/sscribe-admin.js' )
			? filemtime( SSCRIBE_PLUGIN_DIR . 'admin/js/sscribe-admin.js' )
			: SSCRIBE_VERSION;

		$debug_css_version = file_exists( SSCRIBE_PLUGIN_DIR . 'admin/css/sscribe-debug-console.css' )
			? filemtime( SSCRIBE_PLUGIN_DIR . 'admin/css/sscribe-debug-console.css' )
			: SSCRIBE_VERSION;

		$debug_js_version = file_exists( SSCRIBE_PLUGIN_DIR . 'admin/js/sscribe-debug-console.js' )
			? filemtime( SSCRIBE_PLUGIN_DIR . 'admin/js/sscribe-debug-console.js' )
			: SSCRIBE_VERSION;

		wp_enqueue_style(
			'sscribe-admin',
			SSCRIBE_PLUGIN_URL . 'admin/css/sscribe-admin.css',
			array(),
			$css_version
		);

		// Manrope was removed; the admin UI now uses the system font stack
		// (declared in --sscribe-font-family in sscribe-admin.css). No
		// @font-face declarations are needed here.

		wp_enqueue_script(
			'sscribe-admin',
			SSCRIBE_PLUGIN_URL . 'admin/js/sscribe-admin.js',
			array( 'jquery' ),
			$js_version,
			true
		);

		// Debug console assets: only enqueue when the debug logging is
		// actually enabled. Saves ~20-30 KB of JS+CSS on every export
		// page load for the common case where the admin never enabled
		// debug. The toggle in the Debug tab flips a runtime flag; if
		// the user enables debug from a non-debug session, the next
		// page load will pick the assets up.
		$debug_enabled = (bool) get_option( 'sscribe_debug_enabled', false );
		if ( $debug_enabled ) {
			wp_enqueue_style(
				'sscribe-debug-console',
				SSCRIBE_PLUGIN_URL . 'admin/css/sscribe-debug-console.css',
				array( 'sscribe-admin' ),
				$debug_css_version
			);

			wp_enqueue_script(
				'sscribe-debug-console',
				SSCRIBE_PLUGIN_URL . 'admin/js/sscribe-debug-console.js',
				array( 'jquery', 'sscribe-admin' ),
				$debug_js_version,
				true
			);
		}

		add_action( 'admin_print_footer_scripts', array( $this, 'print_localized_data' ), 0 );
	}

	/**
	 * Print localized JS data with CSP nonce attribute.
	 *
	 * WordPress's wp_localize_script() outputs inline <script> tags without a
	 * CSP nonce attribute because the output goes through print_extra_script(),
	 * which hardcodes the tag. This method deliberately replaces that approach by
	 * printing the data manually with the per-request CSP nonce.
	 *
	 * Hooks at priority 0 so it fires before wp_print_footer_scripts (priority 20).
	 */
	public function print_localized_data(): void {
		$screen = get_current_screen();
		if ( ! $screen || 'toplevel_page_sscribe-export' !== $screen->id ) {
			return;
		}

		$nonce = $this->get_csp_nonce();
		if ( empty( $nonce ) ) {
			return;
		}

		$data = array(
			'ajaxurl'         => admin_url( 'admin-ajax.php' ),
			'nonce'           => wp_create_nonce( 'sscribe_export_nonce' ),
			'download_nonce'  => $this->get_download_nonce(),
			'icons_url'       => SSCRIBE_PLUGIN_URL . 'assets/icons/',
			// Auto-refresh interval (ms) for the debug console. Filterable so
			// admins can throttle it down on slow servers or up on fast ones.
			// Enforce a hard minimum of 5 seconds (5000ms) here so a buggy or
			// malicious filter returning 0/negative cannot create a tight
			// infinite loop hammering the AJAX endpoint.
			'refresh_interval' => max( 5000, (int) apply_filters( 'sscribe_debug_refresh_interval_ms', 10000 ) ),
			'strings'        => array(
				'starting'               => __( 'Starting export...', 'sscribe-export-site-pages' ),
				'processing'             => __( 'Processing...', 'sscribe-export-site-pages' ),
				'complete'               => __( 'Export complete!', 'sscribe-export-site-pages' ),
				'error'                  => __( 'An error occurred. Please try again.', 'sscribe-export-site-pages' ),
				'download'               => __( 'Download ZIP', 'sscribe-export-site-pages' ),
				'generating'             => __( 'Generating documents...', 'sscribe-export-site-pages' ),
				'confirm_export'         => __( 'Start exporting pages?', 'sscribe-export-site-pages' ),
				'confirm_delete'         => __( 'Delete this export file?', 'sscribe-export-site-pages' ),
				'auto_delete'            => __( 'This file will be automatically deleted in 72 hours for security.', 'sscribe-export-site-pages' ),
				'cancel'                 => __( 'Cancel Export', 'sscribe-export-site-pages' ),
				'cancelling'             => __( 'Cancelling...', 'sscribe-export-site-pages' ),
				'loading_log'            => __( 'Loading log...', 'sscribe-export-site-pages' ),
				'log_not_found'          => __( 'Log not found.', 'sscribe-export-site-pages' ),
				'log_load_failed'        => __( 'Failed to load log.', 'sscribe-export-site-pages' ),
				'delete_failed'          => __( 'Failed to delete export.', 'sscribe-export-site-pages' ),
				'delete_success'         => __( 'Export deleted.', 'sscribe-export-site-pages' ),
				'history_empty'          => __( 'Your recent export packages will appear here.', 'sscribe-export-site-pages' ),
				'estimated_time'         => __( 'Estimated time:', 'sscribe-export-site-pages' ),
				'minutes'                => __( 'minutes', 'sscribe-export-site-pages' ),
				'minute'                 => __( 'minute', 'sscribe-export-site-pages' ),
				'seconds'                => __( 'seconds', 'sscribe-export-site-pages' ),
				'sec_remaining'          => __( 'sec remaining', 'sscribe-export-site-pages' ),
				/* translators: %1$d: minutes, %2$d: seconds */
				'min_sec_remaining'      => __( '%1$d min %2$d sec remaining', 'sscribe-export-site-pages' ),
				'hour_suffix'            => __( 'h', 'sscribe-export-site-pages' ),
				'minute_suffix'          => __( 'm', 'sscribe-export-site-pages' ),
				'log_total'              => __( 'Total:', 'sscribe-export-site-pages' ),
				'log_pages'              => __( 'pages', 'sscribe-export-site-pages' ),
				'log_success_label'      => __( 'Success:', 'sscribe-export-site-pages' ),
				'log_failed_label'       => __( 'Failed:', 'sscribe-export-site-pages' ),
				'log_page_details'       => __( 'Page Details', 'sscribe-export-site-pages' ),
				'log_col_id'             => __( 'ID', 'sscribe-export-site-pages' ),
				'log_col_title'          => __( 'Title', 'sscribe-export-site-pages' ),
				'log_col_status'         => __( 'Status', 'sscribe-export-site-pages' ),
				'log_col_time'           => __( 'Time', 'sscribe-export-site-pages' ),
				'log_col_formats'        => __( 'Formats', 'sscribe-export-site-pages' ),
				'log_unknown'            => __( 'Unknown', 'sscribe-export-site-pages' ),
				'log_errors'             => __( 'Errors', 'sscribe-export-site-pages' ),
				'log_seconds_suffix'     => __( 's', 'sscribe-export-site-pages' ),
				'packaging'              => __( 'Packaging files into ZIP archive...', 'sscribe-export-site-pages' ),
				'download_tooltip'       => __( 'Download this export', 'sscribe-export-site-pages' ),
				'log_tooltip'            => __( 'View export log', 'sscribe-export-site-pages' ),
				'delete_tooltip'         => __( 'Delete this export', 'sscribe-export-site-pages' ),
				'support_title'          => __( 'Support Information', 'sscribe-export-site-pages' ),
				'err_permission'         => __( 'Your WordPress user role does not have the required capability (sscribe_export). Please contact your site administrator to grant export permissions, or log in with an Administrator account.', 'sscribe-export-site-pages' ),
				'err_session_expired'    => __( 'The export session was lost — this typically happens when the PHP session or database connection timed out. Click "Try Again" to start a fresh export. If this keeps happening, ask your hosting provider to increase the PHP max_execution_time (recommended: 120s or higher).', 'sscribe-export-site-pages' ),
				'err_data_corrupted'     => __( 'The session data in the database became invalid. This can happen if your database ran out of storage or a caching plugin (e.g., WP Rocket, W3 Total Cache) is caching wp_options. Exclude "sscribe_session_*" from object caching.', 'sscribe-export-site-pages' ),
				'err_rate_limit'         => __( 'You have exceeded the request rate limit (200 requests per minute). Please wait about 1 minute and then try again. This limit protects your server from overload.', 'sscribe-export-site-pages' ),
				'err_no_pages'           => __( 'No pages match the selected language and status combination. Go back and verify your selection. If using WPML, ensure the selected language has pages assigned to it.', 'sscribe-export-site-pages' ),
				'err_zip'                => __( 'The server could not create the ZIP archive. Common causes: the uploads directory is not writable (check folder permissions, should be 755), the server ran out of disk space, or the PHP zip extension is not installed. Contact your hosting provider if this persists.', 'sscribe-export-site-pages' ),
				'err_timeout'            => __( 'The server took too long to respond. This usually happens with large pages or slow server hardware. The plugin processes pages individually and will resume from where it left off. If this keeps happening, ask your hosting provider to increase max_execution_time to at least 120 seconds.', 'sscribe-export-site-pages' ),
				'err_memory'             => __( 'The server ran out of PHP memory during export. Ask your hosting provider to increase the WordPress memory limit (WP_MEMORY_LIMIT) to at least 256M. You can also try exporting fewer pages at a time by selecting a specific language.', 'sscribe-export-site-pages' ),
				'err_connection'         => __( 'The connection to your server was interrupted. Check your internet connection and try again. If you are behind a proxy or CDN (e.g., Cloudflare), ensure AJAX requests are not being blocked or cached.', 'sscribe-export-site-pages' ),
				'err_invalid_lang'       => __( 'The selected language code is not recognized by WPML. Go back to step 1 and select a valid language. If you recently changed your WPML configuration, refresh this page first.', 'sscribe-export-site-pages' ),
				'err_in_progress'        => __( 'A previous export session is still active. Click "Try Again" to force-clear it and start fresh.', 'sscribe-export-site-pages' ),
				'err_500'                => __( 'Your server encountered an internal error (HTTP 500). Check your server\'s PHP error log for details. Common causes: a conflicting plugin, PHP memory limit too low, or a corrupted .htaccess file.', 'sscribe-export-site-pages' ),
				'err_403'                => __( 'The server rejected the request (HTTP 403 Forbidden). This is usually caused by a security plugin (e.g., Wordfence, Sucuri, iThemes Security) or server-level firewall blocking AJAX requests. Whitelist the SScribe AJAX actions in your security plugin settings.', 'sscribe-export-site-pages' ),
				'err_generic'            => __( 'Click "Try Again" to retry the export. If the problem continues: refresh the page, check your browser\'s developer console (F12), or contact your hosting provider to review PHP error logs.', 'sscribe-export-site-pages' ),
				'net_connection_lost'    => __( 'Connection lost — the server did not respond. Please check your internet connection and try again.', 'sscribe-export-site-pages' ),
				'net_403'                => __( 'Access denied (HTTP 403). A security plugin or firewall may be blocking this request.', 'sscribe-export-site-pages' ),
				'net_500'                => __( 'Internal server error (HTTP 500). The server encountered a problem — check your PHP error log for details.', 'sscribe-export-site-pages' ),
				'net_502'                => __( 'Bad gateway (HTTP 502). Your server or reverse proxy (Nginx/Cloudflare) is unavailable. Please wait a moment and try again.', 'sscribe-export-site-pages' ),
				'net_503'                => __( 'Service unavailable (HTTP 503). Your server is temporarily overloaded or under maintenance. Please wait a moment and try again.', 'sscribe-export-site-pages' ),
				'net_504'                => __( 'Gateway timeout (HTTP 504). The request took too long to process. Ask your hosting provider to increase the PHP max_execution_time.', 'sscribe-export-site-pages' ),
				'net_timeout'            => __( 'Request timed out — the server took too long to respond. This may happen with large exports. Please try again.', 'sscribe-export-site-pages' ),
				/* translators: %d: HTTP status code */
				'net_unknown'            => __( 'A network error occurred (HTTP %d). Please check your connection and try again.', 'sscribe-export-site-pages' ),
				'support_loading'        => __( 'Loading support information...', 'sscribe-export-site-pages' ),
				'support_error'          => __( 'Unable to load support information right now.', 'sscribe-export-site-pages' ),
				'support_copy_error'     => __( 'Copy failed. Try selecting the text manually.', 'sscribe-export-site-pages' ),
				'support_copy'           => __( 'Copy support info', 'sscribe-export-site-pages' ),
				'support_copied'         => __( 'Support information copied.', 'sscribe-export-site-pages' ),
				'support_refresh'        => __( 'Refresh', 'sscribe-export-site-pages' ),
				'support_generated'      => __( 'Generated', 'sscribe-export-site-pages' ),
				'support_debug'          => __( 'Debug mode may expose extra detail intended for administrators only.', 'sscribe-export-site-pages' ),
				'preflight_title'        => __( 'Export Readiness Check', 'sscribe-export-site-pages' ),
				'preflight_errors'       => __( 'Critical Issues', 'sscribe-export-site-pages' ),
				'preflight_warnings'     => __( 'Recommendations', 'sscribe-export-site-pages' ),
				'preflight_continue'     => __( 'Continue Anyway', 'sscribe-export-site-pages' ),
				'preflight_cancel'       => __( 'Cancel Export', 'sscribe-export-site-pages' ),
				'close'                  => __( 'Close', 'sscribe-export-site-pages' ),
				'generating_preview'     => __( 'Generating preview...', 'sscribe-export-site-pages' ),
				'preview_note'           => __( 'Preview is generated from the first page and may differ from the final export.', 'sscribe-export-site-pages' ),
				'preview_total_pages'    => __( 'Total pages:', 'sscribe-export-site-pages' ),
				'preview_format'         => __( 'Format:', 'sscribe-export-site-pages' ),
				'preview_language'       => __( 'Language:', 'sscribe-export-site-pages' ),
				'preview_status'         => __( 'Status:', 'sscribe-export-site-pages' ),
				'preview_estimated_time' => __( 'Estimated time:', 'sscribe-export-site-pages' ),
				'preview_file_size'      => __( 'Est. file size:', 'sscribe-export-site-pages' ),
				'preview_sample_title'   => __( 'Sample:', 'sscribe-export-site-pages' ),
				'preview_fallback_note'  => __( 'Only the first few pages are shown in the preview.', 'sscribe-export-site-pages' ),
				'summary_time_hint'      => __( 'See Preview for adaptive estimate', 'sscribe-export-site-pages' ),
				'loading_counts'         => __( 'Loading page counts...', 'sscribe-export-site-pages' ),
				'log_diagnostics'        => __( 'Diagnostics', 'sscribe-export-site-pages' ),
				'technical_details'      => __( 'Technical details', 'sscribe-export-site-pages' ),
				'fix_steps'              => __( 'Steps to fix:', 'sscribe-export-site-pages' ),
				'export_progress_prefix' => __( 'Export progress:', 'sscribe-export-site-pages' ),
				'format_docx'            => __( 'Word Document (DOCX)', 'sscribe-export-site-pages' ),
				'format_pdf'             => __( 'PDF Document', 'sscribe-export-site-pages' ),
				'format_html'            => __( 'HTML Page', 'sscribe-export-site-pages' ),
				'format_markdown'        => __( 'Markdown', 'sscribe-export-site-pages' ),
				'err_clear_session'      => __( 'Failed to clear the export session after multiple attempts. Please refresh the page and try again.', 'sscribe-export-site-pages' ),
				'export_cancelled'       => __( 'Export cancelled.', 'sscribe-export-site-pages' ),
				'export_complete_notice' => __( 'Export complete! You can start a new export now.', 'sscribe-export-site-pages' ),
				'click_again'            => __( 'Click again', 'sscribe-export-site-pages' ),
				'selected'               => __( 'selected', 'sscribe-export-site-pages' ),
				'calculating_time'       => __( 'Calculating...', 'sscribe-export-site-pages' ),
				'dismiss_notification'   => __( 'Dismiss notification', 'sscribe-export-site-pages' ),
				'preview_error'          => __( 'Failed to generate preview.', 'sscribe-export-site-pages' ),
				'download_unavailable'   => __( 'Download unavailable.', 'sscribe-export-site-pages' ),
				/* translators: %1$d: current page number, %2$d: total pages */
				'progress_pages'         => __( 'Processing %1$d of %2$d pages', 'sscribe-export-site-pages' ),
				/* translators: %d: progress percentage (e.g. 42) */
				'document_title'         => __( '(%d%%) SScribe Export', 'sscribe-export-site-pages' ),
				'err_cancel_failed'      => __( 'Could not confirm cancellation — the server may still be processing. Reload the page before starting a new export.', 'sscribe-export-site-pages' ),
				// Post-type labels for the live config-summary chips.
				'post_type_page'         => __( 'Pages', 'sscribe-export-site-pages' ),
				'post_type_post'         => __( 'Posts', 'sscribe-export-site-pages' ),
				'post_type_any'          => __( 'Both', 'sscribe-export-site-pages' ),
				// Post-status labels for the live config-summary chips.
				'status_publish'         => __( 'Published', 'sscribe-export-site-pages' ),
				'status_draft'           => __( 'Draft', 'sscribe-export-site-pages' ),
				'status_private'         => __( 'Private', 'sscribe-export-site-pages' ),
				'status_future'          => __( 'Scheduled', 'sscribe-export-site-pages' ),
				'status_pending'         => __( 'Pending', 'sscribe-export-site-pages' ),
				'status_all'             => __( 'All', 'sscribe-export-site-pages' ),
				// Live-region announcements (mirrors progress_pages template style).
				/* translators: 1: page count, 2: "pages" label */
				'live_region_ready'      => __( '%1$d %2$s ready for export', 'sscribe-export-site-pages' ),
				'live_region_no_pages'   => __( 'No pages match selected options. Export button is disabled.', 'sscribe-export-site-pages' ),
				/* translators: 1: prefix (e.g. "Export progress:"), 2: percentage */
				'live_region_progress'   => __( '%1$s %2$d%%', 'sscribe-export-site-pages' ),
			),
		);

		?>
		<script nonce="<?php echo esc_attr( $nonce ); ?>">
		var sscribe_data = <?php echo wp_json_encode( $data, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_HEX_APOS ); ?>;
		</script>
		<?php
	}

	/**
	 * Render the main admin export page.
	 */
	public function render_admin_page(): void {

		$cache_key        = 'sscribe_admin_page_data_v' . SSCRIBE_VERSION . '_' . get_current_blog_id();
		$cached_page_data = get_transient( $cache_key );

		if ( is_array( $cached_page_data ) ) {
			$sscribe_wpml_active     = $cached_page_data['wpml_active'] ?? false;
			$sscribe_languages       = $cached_page_data['languages'] ?? array();
			$sscribe_total_pages_all = $cached_page_data['total_pages_all'] ?? 0;
			$sscribe_status_counts   = $cached_page_data['status_counts'] ?? array();
		} else {

			$sscribe_wpml_active = $this->collector->is_wpml_active();
			$sscribe_languages   = $this->collector->get_wpml_languages();

			$sscribe_total_pages_all = $this->collector->get_page_count_only( '', 'publish' );

			$default_language      = '';
			$sscribe_status_counts = $this->collector->get_post_status_counts( $default_language );

			if ( $sscribe_wpml_active && ! empty( $sscribe_languages ) ) {
				foreach ( $sscribe_languages as &$lang ) {
					if ( isset( $lang['code'] ) ) {
						$lang['page_count'] = $this->collector->get_page_count_only( $lang['code'], 'publish' );
					}
				}
				unset( $lang );
			}

			set_transient(
				$cache_key,
				array(
					'wpml_active'     => $sscribe_wpml_active,
					'languages'       => $sscribe_languages,
					'total_pages_all' => $sscribe_total_pages_all,
					'status_counts'   => $sscribe_status_counts,
				),
				60
			);
		}

		$sscribe_debug_info = array();
		// Always show the debug tab so users can toggle debug on/off.
		// The debug *logging* is still controlled by the setting.
		$sscribe_is_debug             = true;
		$sscribe_debug_logging_active = SSCRIBE_DEBUG || SScribe_Settings::is_debug_enabled();

		if ( $sscribe_debug_logging_active ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log( 'SScribe: Debug mode is ENABLED. This should NOT be enabled in production environments.' ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- Intentional debug warning.
			}
		}

		if ( $sscribe_debug_logging_active ) {
			// Include blog ID in cache key for multisite compatibility.
			$blog_id            = is_multisite() ? get_current_blog_id() : 0;
			$debug_cache_key    = 'sscribe_debug_info_' . $blog_id . '_' . get_current_user_id();
			$sscribe_debug_info = get_transient( $debug_cache_key );

			if ( false === $sscribe_debug_info ) {
				$sscribe_debug_info = $this->gather_debug_info( $sscribe_wpml_active, $sscribe_languages, $sscribe_total_pages_all, $sscribe_status_counts );
				set_transient( $debug_cache_key, $sscribe_debug_info, 30 );
			}
		}

		$upload_dir = wp_upload_dir();
		$export_dir = trailingslashit( $upload_dir['basedir'] ) . 'sscribe-exports/';

		$sscribe_export_index = get_option( 'sscribe_export_index', array() );
		if ( ! is_array( $sscribe_export_index ) ) {
			$sscribe_export_index = array();
		}

		$sscribe_recent_exports = ! empty( $sscribe_export_index )
			? $this->build_recent_exports( $sscribe_export_index, $export_dir, $sscribe_wpml_active, $sscribe_languages, get_current_user_id() )
			: array();

		include SSCRIBE_PLUGIN_DIR . 'admin/partials/sscribe-admin-display.php';
	}

	/**
	 * Build recent export data for the admin history table.
	 *
	 * @param array  $export_index Export index option value.
	 * @param string $export_dir Export directory path.
	 * @param bool   $wpml_active Whether WPML is active.
	 * @param array  $languages WPML language metadata.
	 * @param int    $user_id Current user ID.
	 * @return array Recent export rows.
	 */
	private function build_recent_exports( array $export_index, string $export_dir, bool $wpml_active, array $languages, int $user_id ): array {
		uasort(
			$export_index,
			static function ( $a, $b ): int {
				$a_time = is_array( $a ) ? (int) ( $a['created_at'] ?? 0 ) : 0;
				$b_time = is_array( $b ) ? (int) ( $b['created_at'] ?? 0 ) : 0;

				return $b_time <=> $a_time;
			}
		);

		$language_map = array();
		foreach ( $languages as $language ) {
			if ( ! is_array( $language ) || empty( $language['code'] ) ) {
				continue;
			}
			$language_map[ sanitize_key( (string) $language['code'] ) ] = $language;
		}

		$recent_exports = array();

		// Pre-collect existing files to avoid O(n) file_exists() calls on slow filesystems.
		$existing_files = array();
		if ( is_dir( $export_dir ) ) {
			$glob_files = glob( trailingslashit( $export_dir ) . '*.zip' );
			$glob_files = is_array( $glob_files ) ? $glob_files : array();
			foreach ( $glob_files as $f ) {
				$existing_files[ basename( $f ) ] = true;
			}
		}

		foreach ( $export_index as $filename => $data ) {
			if ( ! is_array( $data ) ) {
				continue;
			}

			if ( isset( $data['user_id'] ) && (int) $data['user_id'] !== $user_id ) {
				continue;
			}

			$filename = basename( sanitize_file_name( (string) $filename ) );
			if ( '' === $filename || 'zip' !== strtolower( pathinfo( $filename, PATHINFO_EXTENSION ) ) ) {
				continue;
			}

			$file_path = $export_dir . $filename;
			if ( ! isset( $existing_files[ $filename ] ) ) {
				continue;
			}

			$real_path = realpath( $file_path );
			$real_dir  = realpath( $export_dir );
			if ( false === $real_path || false === $real_dir ) {
				continue;
			}
			$safe_dir = rtrim( $real_dir, DIRECTORY_SEPARATOR ) . DIRECTORY_SEPARATOR;
			if ( ! str_starts_with( $real_path, $safe_dir ) ) {
				continue;
			}

			$lang_code = sanitize_key( (string) ( $data['lang_code'] ?? '' ) );
			// lang_code is populated for every new export by the batch
			// processor. The filename no longer carries a `-LANG` suffix
			// (the language is communicated by the per-language subdir
			// inside the ZIP), so a regex-based fallback would either
			// be dead code or mis-parse format tokens. Trust the index.

			if ( '' === $lang_code ) {
				$lang_code = 'all';
			}

			$lang_name = sanitize_text_field( (string) ( $data['lang_name'] ?? '' ) );
			$flag_url  = esc_url_raw( (string) ( $data['flag_url'] ?? '' ) );

			if ( 'all' === $lang_code ) {
				$lang_name = __( 'All Languages', 'sscribe-export-site-pages' );
			} elseif ( $wpml_active && isset( $language_map[ $lang_code ] ) ) {
				$lang_name = sanitize_text_field( (string) ( $language_map[ $lang_code ]['name'] ?? strtoupper( $lang_code ) ) );
				$flag_url  = esc_url_raw( (string) ( $language_map[ $lang_code ]['flag_url'] ?? $flag_url ) );
			} elseif ( '' === $lang_name ) {
				$lang_name = strtoupper( $lang_code );
			}

			$recent_exports[] = array(
				'filename'  => $filename,
				'url'       => $this->zip_handler->get_ajax_download_url( $filename ),
				'time' => isset( $data['created_at'] ) ? (int) $data['created_at'] : (int) filemtime( $file_path ),
				'size'      => (int) filesize( $file_path ),
				'lang_code' => $lang_code,
				'flag_url'  => $flag_url,
				'lang_name' => $lang_name,
			);

			if ( count( $recent_exports ) >= 10 ) {
				break;
			}
		}

		return $recent_exports;
	}

	/**
	 * Gather debug information for the admin page.
	 *
	 * @param bool  $wpml_active       Whether WPML is active.
	 * @param array $languages         Language list.
	 * @param int   $total_pages_all   Total published pages.
	 * @param array $status_counts     Post status counts.
	 * @return array Debug information.
	 */
	private function gather_debug_info( bool $wpml_active, array $languages, int $total_pages_all, array $status_counts ): array {
		$sscribe_debug_info                    = array();
		$sscribe_debug_info['languages_count'] = count( $languages );
		$sscribe_debug_info['total_pages_all'] = $total_pages_all;
		$sscribe_debug_info['status_counts']   = $status_counts;
		$sscribe_debug_info['duplicate_slugs'] = array();

		if ( $wpml_active && ! empty( $languages ) ) {
			$all_page_ids_by_lang = array();

			foreach ( $languages as $lang ) {
				$lang_code = $lang['code'];
				$sscribe_debug_info['language_details'][ $lang_code ] = array(
					'name'             => $lang['name'],
					'page_count'       => $lang['page_count'] ?? 0,
					'status_breakdown' => $this->collector->get_post_status_counts( $lang_code ),
				);

				// Limit to 50 IDs per language to prevent expensive queries on large multilingual sites.
				// Use get_page_count_only() for the total count, and only fetch IDs when needed for slug checks.
				$sscribe_debug_info['language_details'][ $lang_code ]['published_count'] = $this->collector->get_page_count_only( $lang_code, 'publish' );
				$page_ids = $this->collector->get_page_ids( $lang_code, 'publish', 'page', 50 );
				$sscribe_debug_info['language_details'][ $lang_code ]['published_page_ids'] = $page_ids;
				$all_page_ids_by_lang[ $lang_code ] = $page_ids;
			}

			$all_slugs    = array();
			$all_flat_ids = array();
			foreach ( $all_page_ids_by_lang as $lang_code => $ids ) {
				foreach ( $ids as $pid ) {
					$all_flat_ids[] = array(
						'id'   => $pid,
						'lang' => $lang_code,
					);
				}
			}

			$all_id_list = array_column( $all_flat_ids, 'id' );
			if ( count( $all_id_list ) > 200 ) {
				$all_id_list = array_slice( $all_id_list, 0, 200 );
			}
			$posts_by_id = array();
			if ( ! empty( $all_id_list ) ) {
				$batch_posts = get_posts(
					array(
						'post__in'               => $all_id_list,
						'post_type'              => 'page',
						'post_status'            => 'any',
						'posts_per_page'         => 200,
						'no_found_rows'          => true,
						'update_post_meta_cache' => false,
						'update_post_term_cache' => false,
						'orderby'                => 'post__in',
					)
				);

				if ( is_array( $batch_posts ) && ! empty( $batch_posts ) ) {
					foreach ( $batch_posts as $post ) {
						$posts_by_id[ $post->ID ] = $post;
					}
				}
			}

			foreach ( $all_flat_ids as $entry ) {
				$pid  = $entry['id'];
				$lc   = $entry['lang'];
				$post = $posts_by_id[ $pid ] ?? null;
				if ( $post ) {
					$slug = $post->post_name;
					if ( ! isset( $all_slugs[ $slug ] ) ) {
						$all_slugs[ $slug ] = array();
					}
					$all_slugs[ $slug ][] = array(
						'id'    => $pid,
						'lang'  => $lc,
						'title' => $post->post_title,
					);
				}
			}
			$sscribe_debug_info['duplicate_slugs'] = array_filter(
				$all_slugs,
				function ( $items ) {
					return count( $items ) > 1;
				}
			);
		}

		$sscribe_debug_info['server'] = array(
			'php_version'         => PHP_VERSION,
			'memory_limit'        => ini_get( 'memory_limit' ),
			'max_execution_time'  => ini_get( 'max_execution_time' ),
			'upload_max_filesize' => ini_get( 'upload_max_filesize' ),
			'post_max_size'       => ini_get( 'post_max_size' ),
		);

		$sscribe_debug_info['wordpress'] = array(
			'version' => get_bloginfo( 'version' ),
			'locale'  => get_locale(),
		);

		return $sscribe_debug_info;
	}

	/**
	 * Add quick action links to the plugin entry.
	 *
	 * @param array $links Existing plugin action links.
	 * @return array Modified links array.
	 */
	public function add_plugin_action_links( array $links ): array {
		$plugin_links = array(
			'<a href="' . esc_url( admin_url( 'admin.php?page=sscribe-export' ) ) . '">' . esc_html__( 'Export Pages', 'sscribe-export-site-pages' ) . '</a>',
		);
		return array_merge( $plugin_links, $links );
	}
}
