<?php
/**
 * Phase 36: source / build transparency contract.
 *
 * The shipped ZIP is generated by Composer (dependency resolution +
 * autoloader), Strauss (namespace prefixing), and a custom build script
 * (comment stripping, dev-path pruning, font subsetting, AI-artifact
 * sanitization). WordPress.org reviewers must be able to understand
 * and reproduce the build from the public source repository. This
 * verifier enforces the contract end-to-end:
 *
 *  1. The public source repository is referenced from readme.txt.
 *  2. readme.txt carries a Development section that lists every
 *     required tool (PHP, Composer, Node, Git) with a version floor.
 *  3. readme.txt lists the exact build commands a reviewer would run
 *     to reproduce the ZIP (`composer install`, `composer vendor:prefix`,
 *     `composer release`).
 *  4. composer.json declares a PHP version floor in `require`.
 *  5. composer.lock is committed alongside composer.json so dependency
 *     versions are pinned and reproducible.
 *  6. package.json declares a Node version floor in `engines`.
 *  7. scripts/build-release.php — the build script — exists and is the
 *     script wired to `composer release`.
 *  8. docs/BUILD_TRANSFORMATIONS.md exists with the canonical section
 *     headings (Excluded paths, In-place file transformations,
 *     Vendor-specific rewrites) so a reviewer can audit every
 *     transformation the build applies.
 *  9. The mainfile Author URI is set to a real URL (the public author
 *     page), not left blank.
 * 10. The WP.org Developer Guidelines reference is reachable from
 *     readme.txt (link to the canonical guidelines URL).
 *
 * A regression that drops the source URL, removes the Development
 * section, unpins tool versions, deletes the build doc, or strips the
 * build script fails this verifier and never reaches submission.
 *
 * The verifier exits 0 on full contract compliance and 1 on any
 * violation, with one line per violation so PHPUnit can grep for the
 * rule keyword.
 *
 * @package SScribe_Export_Site_Pages
 */

declare( strict_types=1 );

$root_dir = dirname( __DIR__ );

$errors = array();

echo "=== SScribe Build Transparency ===\n\n";

/**
 * Helper: assert a file exists; push a one-line violation on failure.
 */
$must_exist = static function ( string $path, string $label ) use ( &$errors ): bool {
	if ( ! is_file( $path ) ) {
		$errors[] = "[{$label}] required file missing: {$path}";
		return false;
	}
	return true;
};

/**
 * Helper: pull a substring out of a file, case-insensitive.
 */
$file_contains = static function ( string $path, string $needle ): bool {
	$haystack = (string) file_get_contents( $path );
	return false !== stripos( $haystack, $needle );
};

// 1. readme.txt carries a `== Development ==` section that names the
//    public source repository. WP.org reviewers will not trust a
//    submission whose only source pointer is a closed/private repo.
$readme_path = $root_dir . '/readme.txt';
if ( ! $must_exist( $readme_path, 'readme.txt' ) ) {
	// All later readme.txt checks short-circuit on absence.
} else {
	$readme = (string) file_get_contents( $readme_path );

	// 1a. `== Development ==` heading is present.
	if ( ! preg_match( '/^==\s*Development\s*==\s*$/m', $readme ) ) {
		$errors[] = 'readme.txt must contain a `== Development ==` section so reviewers can find the source pointer without reading the changelog.';
	}
	// 1b. The section names a public source repository URL.
	//     We accept any common host (github.com, gitlab.com, codeberg.org,
	//     bitbucket.org) so the rule is portable across hosts.
	$source_url_hosts = array( 'github.com', 'gitlab.com', 'codeberg.org', 'bitbucket.org' );
	$source_url_found = false;
	foreach ( $source_url_hosts as $host ) {
		if ( false !== stripos( $readme, $host ) ) {
			$source_url_found = true;
			break;
		}
	}
	if ( ! $source_url_found ) {
		$errors[] = 'readme.txt Development section must reference a public source repository (github.com / gitlab.com / codeberg.org / bitbucket.org).';
	}
	// 1c. The section lists the exact build commands. A reviewer who
	//     wants to reproduce the ZIP needs `composer install` (or
	//     equivalent) and `composer release` (or the explicit
	//     `scripts/build-release.php` invocation) called out by name.
	$build_command_keywords = array( 'composer install', 'composer release', 'composer vendor:prefix' );
	$missing_commands        = array();
	foreach ( $build_command_keywords as $kw ) {
		if ( false === stripos( $readme, $kw ) ) {
			$missing_commands[] = $kw;
		}
	}
	if ( ! empty( $missing_commands ) ) {
		$errors[] = 'readme.txt Development section must call out the build commands a reviewer runs to reproduce the ZIP. Missing: ' . implode( ', ', $missing_commands ) . '.';
	}
	// 1d. The section pins the major tool versions (PHP, Composer, Node,
	//     Git) so reviewers know what to install.
	$tool_version_keywords = array( 'php', 'composer', 'node' );
	$missing_tools          = array();
	foreach ( $tool_version_keywords as $kw ) {
		if ( false === stripos( $readme, $kw ) ) {
			$missing_tools[] = $kw;
		}
	}
	if ( ! empty( $missing_tools ) ) {
		$errors[] = 'readme.txt Development section must list the required tools (php, composer, node) with version floors. Missing: ' . implode( ', ', $missing_tools ) . '.';
	}
	// 1e. Pointer to docs/BUILD_TRANSFORMATIONS.md so reviewers can drill
	//     down from the public readme into the per-transformation audit.
	if ( false === stripos( $readme, 'BUILD_TRANSFORMATIONS' ) ) {
		$errors[] = 'readme.txt must reference docs/BUILD_TRANSFORMATIONS.md so reviewers can audit every build transformation.';
	}
}

// 2. composer.json declares a PHP version floor in `require`.
$composer_path = $root_dir . '/composer.json';
if ( ! $must_exist( $composer_path, 'composer.json' ) ) {
} else {
	$composer = (string) file_get_contents( $composer_path );
	if ( ! preg_match( '/"require"\s*:\s*\{[^}]*"php"\s*:\s*"\s*>[^"]+"/', $composer ) ) {
		$errors[] = 'composer.json must declare a PHP version floor (e.g. `"php": ">=8.2"`) so reviewers can match their runtime to the contract.';
	}
}

// 3. composer.lock is committed so dependency versions are pinned.
if ( ! is_file( $root_dir . '/composer.lock' ) ) {
	$errors[] = 'composer.lock must be committed so the dependency graph is reproducible across machines. A submission without composer.lock can drift between reviewer and CI.';
}

// 4. package.json declares a Node version floor in `engines`.
$package_path = $root_dir . '/package.json';
if ( ! $must_exist( $package_path, 'package.json' ) ) {
} else {
	$package = (string) file_get_contents( $package_path );
	if ( ! preg_match( '/"engines"\s*:\s*\{[^}]*"node"\s*:\s*"/', $package ) ) {
		$errors[] = 'package.json must declare a Node version floor in `engines` (e.g. `"node": ">=24"`) so a reviewer can install the exact frontend toolchain.';
	}
}

// 5. scripts/build-release.php is the build script.
if ( ! is_file( $root_dir . '/scripts/build-release.php' ) ) {
	$errors[] = 'scripts/build-release.php must exist as the canonical build script (wired to `composer release`).';
}

// 6. docs/BUILD_TRANSFORMATIONS.md exists with the canonical sections.
$build_doc = $root_dir . '/docs/BUILD_TRANSFORMATIONS.md';
if ( ! $must_exist( $build_doc, 'docs/BUILD_TRANSFORMATIONS.md' ) ) {
} else {
	$build_doc_src = (string) file_get_contents( $build_doc );
	$required_headings = array(
		'## 1. Excluded paths',
		'## 2. In-place file transformations',
	);
	foreach ( $required_headings as $heading ) {
		if ( false === strpos( $build_doc_src, $heading ) ) {
			$errors[] = "docs/BUILD_TRANSFORMATIONS.md must contain the canonical section `{$heading}`.";
		}
	}
}

// 7. The mainfile Author URI is set to a real URL (not blank).
$mainfile_path = $root_dir . '/sscribe-export-site-pages.php';
if ( ! $must_exist( $mainfile_path, 'sscribe-export-site-pages.php' ) ) {
} else {
	$mainfile = (string) file_get_contents( $mainfile_path );
	if ( ! preg_match( '/Author URI:\s*(https?:\/\/\S+)/', $mainfile, $m ) ) {
		$errors[] = 'sscribe-export-site-pages.php must declare an Author URI pointing at a real URL — WP.org reviewers rely on it to verify authorship.';
	}
}

if ( empty( $errors ) ) {
	echo "✓ Build transparency holds. readme.txt names the source repo, lists the build commands and tool versions; composer.json pins PHP; composer.lock is committed; package.json pins Node; scripts/build-release.php is the build script; docs/BUILD_TRANSFORMATIONS.md documents every transformation.\n";
	exit( 0 );
}

echo "Errors:\n";
foreach ( $errors as $error ) {
	echo "  ✗ {$error}\n";
}
echo "\n";
exit( 1 );
